version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: mysql8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - .docker/db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_ROOT_HOST: '%'
